<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="CSharpier.MsBuild" Version="1.0.2" />
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="9.5.1" />
    <PackageVersion Include="Aspire.OpenAI" Version="9.5.1-preview.1.25502.11" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.SQLite" Version="9.8.0" />
    <PackageVersion Include="CommunityToolkit.Aspire.Microsoft.Data.Sqlite" Version="9.8.0" />
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-preview.251009.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.251009.1" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="9.9.1" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="9.9.1-preview.1.25474.6" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.9.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="9.5.1" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.13.1" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.13.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.12.0" />
  </ItemGroup>
</Project>